### ISSUE TITLE
[FTBS

### ISSUE THREAD

**Issue by Corin-EU** [TTK-qmmp/qmmp-blurxrays#1]
latest revision 8ae45b4

The header file "ui_colorwidget.h" has gone missing.

In the directory common,  the source file colorwidget.cpp has the line

                       #include "ui_colorwidget.h"

but the header file ui_colorwidget.h is nowhere to be found in the source code directory tree.

**Comment by Greedysky** [comment]
Fixed

**Comment by Corin-EU** [comment]
Thank you for the fix.   I see now that the "missing" header file is actually created dynamically in the make operation (provided that the Makefile has been properly generated by qmake from the project file). 

               /usr/lib64/qt5/bin/uic  common/colorwidget.ui  -o ui_colorwidget.h
