### ISSUE TITLE
is an update for Qt6 planned so that TTK qmmp-plugins will work with version 2 series of qmmp?

### ISSUE THREAD

**Issue by Corin-EU** [TTK-qmmp/qmmp-blurxrays#3]
Most of the TTK-qmmp plugins can only be build with Qt5 (which is used for the version 1 series of QMMP).

Any chance of updates for Qt6 on which the version 2 series of QMMP is based?

`
g++-13 -c -pipe -O2 -std=gnu++1z -D_REENTRANT -w -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -Icommon -Icommon -I/usr/local/include -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I. -I. -I/usr/include/qt6/QtWidgets -I/usr/local/include/libbinio -I/usr/local/include/qmmp -I/usr/include -I/usr/lib64/qt6/mkspecs/linux-g++ -o colorwidget.o common/colorwidget.cpp
common/colorwidget.cpp: In static member function ‘static QList<QColor> ColorWidget::readColorConfig(const QString&)’:
common/colorwidget.cpp:76:57: error: ‘SkipEmptyParts’ is not a member of ‘QString’
   76 |     const QStringList &rgbs = value.split(';', QString::SkipEmptyParts);
      |                                                         ^~~~~~~~~~~~~~
common/colorwidget.cpp: In member function ‘void ColorWidget::setColors(const QList<QColor>&)’:
common/colorwidget.cpp:111:13: error: ‘class QListWidgetItem’ has no member named ‘setBackgroundColor’; did you mean ‘setBackground’?
  111 |         it->setBackgroundColor(color);
      |             ^~~~~~~~~~~~~~~~~~
      |             setBackground
common/colorwidget.cpp: In member function ‘QList<QColor> ColorWidget::colors() const’:
common/colorwidget.cpp:128:46: error: ‘class QListWidgetItem’ has no member named ‘backgroundColor’; did you mean ‘background’?
  128 |         colors << m_ui->listWidget->item(i)->backgroundColor();
      |                                              ^~~~~~~~~~~~~~~
      |                                              background
common/colorwidget.cpp: In member function ‘void ColorWidget::addButtonClicked()’:
common/colorwidget.cpp:139:13: error: ‘class QListWidgetItem’ has no member named ‘setBackgroundColor’; did you mean ‘setBackground’?
  139 |         it->setBackgroundColor(dialog.selectedColor());
      |             ^~~~~~~~~~~~~~~~~~
      |             setBackground
common/colorwidget.cpp: In member function ‘void ColorWidget::modifyButtonClicked()’:
common/colorwidget.cpp:174:17: error: ‘class QListWidgetItem’ has no member named ‘setBackgroundColor’; did you mean ‘setBackground’?
  174 |             it->setBackgroundColor(dialog.selectedColor());
      |                 ^~~~~~~~~~~~~~~~~~
      |                 setBackground
make: *** [Makefile:505: colorwidget.o] Error 1
'

Other optional plugins which will not build because of changes from Qt5 to Qt6 are blurxrays, mountain, openmpt, and volume.

Surprisingly flowwave, voice, and ym all built successfully.

**Comment by Greedysky** [comment]
Fixed @Corin-EU
